import { useEffect, useState } from 'react';
import { Link2, X } from 'lucide-react';
import toast from 'react-hot-toast';
import type { ReviewPermission } from '../../types';
import { articleReviewService } from '../../services/articleReviewService';
export function ShareDialog({ articleId, onClose }: { articleId: string; onClose: () => void }) {
  const defaultExpiry = () => { const d = new Date(); d.setDate(d.getDate() + 30); d.setMinutes(d.getMinutes() - d.getTimezoneOffset()); return d.toISOString().slice(0, 16); };
  const [permission, setPermission] = useState<ReviewPermission>('comment'); const [url, setUrl] = useState(''); const [loading, setLoading] = useState(false); const [expiresAt, setExpiresAt] = useState(defaultExpiry); const [noExpiry, setNoExpiry] = useState(false); const [password, setPassword] = useState(''); const [links, setLinks] = useState<Array<{ id: string; permission: ReviewPermission; expiresAt?: string | null; revokedAt?: string | null }>>([]);
  const loadLinks = async () => { try { const data = await articleReviewService.listLinks(articleId); setLinks(data.links); } catch { /* 作成操作は継続可能 */ } };
  useEffect(() => { void loadLinks(); }, [articleId]);
  const create = async () => { setLoading(true); try { const { token } = await articleReviewService.createLink(articleId, permission, noExpiry ? undefined : new Date(expiresAt).toISOString(), password || undefined); setUrl(`${location.origin}/review/${token}`); await loadLinks(); } catch (e) { toast.error(e instanceof Error ? e.message : '共有リンクを作成できませんでした'); } finally { setLoading(false); } };
  const revoke = async (id: string) => { try { await articleReviewService.revokeLink(id); toast.success('共有を停止しました'); await loadLinks(); } catch (e) { toast.error(e instanceof Error ? e.message : '共有を停止できませんでした'); } };
  return <div className="fixed inset-0 z-[70] grid place-items-center bg-black/50 p-4"><div className="w-full max-w-lg rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-bold">レビューを共有</h2><p className="text-sm text-gray-500">リンクを知っている人だけに記事を共有します</p></div><button onClick={onClose}><X /></button></div><div className="space-y-5 p-5">{url ? <><input className="input-field" readOnly value={url}/><button className="btn-primary flex w-full justify-center" onClick={async()=>{await navigator.clipboard.writeText(url);toast.success('コピーしました');}}>リンクをコピー</button></> : <><div className="grid grid-cols-3 gap-2">{([['view','閲覧のみ'],['comment','コメント可'],['edit','編集可']] as [ReviewPermission,string][]).map(([v,l])=><button key={v} onClick={()=>setPermission(v)} className={`rounded-lg border p-3 text-sm ${permission===v?'border-blue-600 bg-blue-50 text-blue-700':'border-gray-200'}`}>{l}</button>)}</div><div><label className="mb-1 block text-sm font-medium">有効期限（初期値は30日です）</label><input type="datetime-local" disabled={noExpiry} value={expiresAt} onChange={e=>setExpiresAt(e.target.value)} className="input-field"/><label className="mt-2 flex items-center gap-2 text-sm"><input type="checkbox" checked={noExpiry} onChange={e=>setNoExpiry(e.target.checked)}/>期限なし</label></div><div><label className="mb-1 block text-sm font-medium">パスワード（任意）</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="設定しない場合は空欄" className="input-field"/></div><button className="btn-primary flex w-full justify-center gap-2" disabled={loading} onClick={create}><Link2 className="w-4"/>共有リンクを作成</button></>} {links.filter(link=>!link.revokedAt).length>0&&<div className="border-t pt-4"><p className="mb-2 text-sm font-medium">発行済みリンク</p>{links.filter(link=>!link.revokedAt).map(link=><div key={link.id} className="flex items-center justify-between rounded border p-2 text-sm"><span>{link.permission==='view'?'閲覧のみ':link.permission==='comment'?'コメント可':'編集可'}</span><button onClick={()=>revoke(link.id)} className="text-red-600">共有を停止</button></div>)}</div>}</div></div></div>;
}
